### ISSUE TITLE
How does a User Invite their Therapist

### ISSUE THREAD

**Issue by billiedemott** [akshatpradhan/spoutlets#110]
What's on the page?

**Comment by billiedemott** [comment]
"Invite your therapist to improve your treatment by integrating your journal & graphs. 

1) They get filled in on your issues.  
2) So in your sessions, you can focus on figuring out solutions to your issues. "

<form>Therapist Email</form>

<form> Editable Text Box with Email Copy</form>
  

“Hi Doctor, 

I’d like you to integrate my thought record, and my issue & mood data into my treatment. Please sign up now so you can get secure access to this personal information. I think it will help me a lot.

Click on the link in this email so you can sign up & learn more about how Spoutlets can help me. 

Thanks,

Billie”

**Comment by billiedemott** [comment]
@akshatpradhan - obviously still lots more to do but thought I'd put this in. 

![screen shot 2013-07-18 at 5 50 02 pm](https://f.cloud.github.com/assets/1459738/822632/21520910-eff4-11e2-8312-09f655b6af29.png)

**Comment by akshatpradhan** [comment]
![screen shot 2013-07-22 at 8 35 28 am](https://f.cloud.github.com/assets/331004/834803/39e72e0e-f2cb-11e2-9214-b6d329b94cb4.png)

**Comment by billiedemott** [comment]
@akshatpradhan - good edit!
