### ISSUE TITLE
What does the email to the therapist say? What does it look like? 

### ISSUE THREAD

**Issue by billiedemott** [akshatpradhan/spoutlets#111]
1) Write copy for email
2) What is the basic layout

**Comment by billiedemott** [comment]
Therapist Email Copy

“Hi Doctor, 

I’d like you to integrate my thought record, and the data regarding my issues and moods into my treatment. Please sign up now so you can get secure access to this personal information. I think it will help me a lot.

Click on the link so you can sign up and learn more about Spoutlets. 

Thanks,

Billie”

(Button to navigate them to the Therapist Sign-in Page)

**Comment by akshatpradhan** [comment]
![screen shot 2013-07-22 at 10 35 04 am](https://f.cloud.github.com/assets/331004/835457/fcfbc96c-f2db-11e2-8841-7e9c6fed4278.png)
