### ISSUE TITLE
Iconography for Share with Therapist Page

### ISSUE THREAD

**Issue by billiedemott** [akshatpradhan/spoutlets#117]
@akshatpradhan - 

So I know we are thinking of adding that couch icon at some point cause it's bottomline delighful, but I think in terms of using existing flat ui icons, we can use these two icons for the "share with therapist" icons for now. (Then maybe we get Joanna to take that couch and redesign it to fit with the Flat UI: 

![screen shot 2013-07-20 at 6 53 07 pm](https://f.cloud.github.com/assets/1459738/830987/9fcd55e4-f191-11e2-95e1-046c73d32bb3.png)

My reasoning behind choosing these icons:
1. the check icon imparts that this is a step that needs to be taken; also the magnified part of the check mark embodies the idea of a closer look (ie your shrink gets a closer, more intimate look at you because you share)
2. the "map" icon imparts the idea of a "plan of action" - i think it looks like a blueprint and it also looks like data points that are being connected, which I think embodies a lot of what you want your shrink to do for you. 

Other option: 

![screen shot 2013-07-20 at 6 07 07 pm](https://f.cloud.github.com/assets/1459738/830997/7307a69e-f192-11e2-8c01-ffcc01ccd667.png)

Reasoning: 
1. the book and the ribbon closing it tight obviously make reference to the content a user is sharing - the journal & the fact that it is private. 

Whatdya think? I think we should just use these templates for now - just get this out the door and being used.

**Comment by akshatpradhan** [comment]
![screen shot 2013-07-22 at 6 58 55 am](https://f.cloud.github.com/assets/331004/834438/0ff243c4-f2bf-11e2-91b1-c0098033fd05.png)
