### ISSUE TITLE
@mentions in Journal Entries

### ISSUE THREAD

**Issue by akshatpradhan** [akshatpradhan/spoutlets#138]
Idea for much much later. Instead of a commenting system, what about doing @mentions in your own journal entry to reference someone else. If @mentions are done using usernames instead of realnames, then privacy is retained?

**Comment by billiedemott** [comment]
@akshatpradhan - I agree this could be simpler, but let's definitely think more about this when we've gotten all of our basics down pat. We gots a ways to go before we start bloating up our feature set. ODG.
