### ISSUE TITLE
/entries/new page

### ISSUE THREAD

**Issue by akshatpradhan** [akshatpradhan/spoutlets#21]
Right now, /entries/new looks like this

![Screen Shot 2013-02-12 at 11 01 39 AM](https://f.cloud.github.com/assets/331004/149436/854cc41a-752d-11e2-84cd-dd9b11842bb9.png)

We need it to look like this screenshot, using only simple_form and bootstrap.
![Screen Shot 2013-02-01 at 2 58 46 PM](https://f.cloud.github.com/assets/331004/149433/6e2d3896-752d-11e2-9164-d879aa461069.png)

**Comment by farleyknight** [comment]
Is there any particular reason you would go with dropdowns instead of sliders? Just curious.

**Comment by akshatpradhan** [comment]
MVP, just trying to get something out there, in the next iteration, when I find some good bootstrappy sliders, we'll change it to sliders

**Comment by farleyknight** [comment]
Awesome. Here's something I found that may be helpful in the future: 

http://addyosmani.github.com/jquery-ui-bootstrap

http://addyosmani.github.com/jquery-ui-bootstrap/components.html#slider

**Comment by akshatpradhan** [comment]
Alright, fixed the IA http://spoutletsapp.herokuapp.com/entries/new

I haven't added any validators, etc. yet.
