### ISSUE TITLE
Encrypt content of entry so that only I can view the contents

### ISSUE THREAD

**Issue by akshatpradhan** [akshatpradhan/spoutlets#28]
For the future, it would be good to investigate a way to encrypt the content of people's entries.

**Comment by MarkDBlackwell** [comment]
General encryption of entries would add a layer of protection from general database hacking.

In fact, a simple MD5 hash of all entries by a key known in the source would add a layer of protection from casual eyes.

I suppose a layer of protection from other users only could be added if each user had her own, different encryption key. We wouldn't store those keys in cleartext, but where?

We could use a salted hash of each user's email address to encrypt each user's entries differently from the others. However, there's a danger of losing the salt, and we can't ever change it, or we would lose all the database contents.

The salt could be a key known in the source, and then after retrieving encrypted entries from wherever, we could decrypt by the current user's salted email address. That would add a layer of protection in the code, beyond the layer of selecting the current user's entries only.

Bad is that admin's would be unable to see other user's entries unless we added a line of code to access the salted email address from the other user's record.

What about counselors looking at their patients' entries?
