### ISSUE TITLE
Entry title should appear in Your Journal and Your Community

### ISSUE THREAD

**Issue by billiedemott** [akshatpradhan/spoutlets#48]
FYI, currently the title input during log an entry doesn't appear on the output in Your Journal. 

AP - lmk if you want to discuss placement. I will think about placement.

**Comment by akshatpradhan** [comment]
1. if you type the @akshatpradhan, it will automatically notify me. That's better then using AP. 
2. Can you upload 1 wireframe that shows where the title will go and how it will look? I know you'll be making a ton of variations, but don't show me the variations. Just show me the 1 that you like the most.

**Comment by billiedemott** [comment]
Refer to Gmail Chain: https://mail.google.com/mail/u/0/#inbox/13fcb65d2407efa9

**Comment by billiedemott** [comment]
Refer to email chain: https://mail.google.com/mail/u/0/#inbox/13fcb65d2407efa9

"I think you're right about the title" written on 7/10/13

**Comment by akshatpradhan** [comment]
Closing this as we now have title on the Journal. Still not sure about putting it on the community.
