### ISSUE TITLE
change drop down to slider for mood ratings

### ISSUE THREAD

**Issue by akshatpradhan** [akshatpradhan/spoutlets#49]
We currently use drop downs for the mood ratings
![Screen Shot 2013-03-01 at 11 32 47 AM](https://f.cloud.github.com/assets/331004/210319/b4e369dc-828d-11e2-87e7-38ba33ae646a.png)

We should use some clean, bootstrap, and simple_form friendly sliders. @farleyknight suggested this: http://addyosmani.github.com/jquery-ui-bootstrap/components.html#slider

**Comment by akshatpradhan** [comment]
I think I found our slider. This little slider feels aesthetically pleasing to me. @billiedemott what do you think? http://www.eyecon.ro/bootstrap-slider/

**Comment by MarkDBlackwell** [comment]
@akshatpradhan, I am assuming you mean the "Basic example" at the top.

**Comment by akshatpradhan** [comment]
@MarkDBlackwell Yup, that's what I mean.

**Comment by akshatpradhan** [comment]
Fixed in this pull request https://github.com/akshatpradhan/spoutlets/pull/54
