### ISSUE TITLE
Log an Entry Bug

### ISSUE THREAD

**Issue by billiedemott** [akshatpradhan/spoutlets#52]
Given I'm on http://www.spoutlets.com/entries/new
When I click "Log it"
Then I should see my entry logged in my journal and not this: http://www.spoutlets.com/entries

![Screen Shot 2013-03-04 at 11 26 54 PM](https://f.cloud.github.com/assets/1459738/219921/56fbc116-854e-11e2-87c9-86d08eb91d2b.png)

**Comment by akshatpradhan** [comment]
Fixed
