### ISSUE TITLE
Get Discourse up on server

### ISSUE THREAD

**Issue by akshatpradhan** [akshatpradhan/spoutlets#71]
If I give you access to an ubuntu server, can you get Discourse running on it? 

https://github.com/discourse/discourse/blob/master/docs/DEVELOPER-ADVANCED.md

**Comment by MarkDBlackwell** [comment]
Probably so. Ubuntu is so much like my Debian, and besides, I've even done RedHat installations of things.

Sounds like fun, and I'd love to do it for you and learn Discourse besides. :)
