### ISSUE TITLE
page after login should be journal, not community

### ISSUE THREAD

**Issue by akshatpradhan** [akshatpradhan/spoutlets#92]
Given I'm on http://www.spoutlets.com
When I login
Then I should see my profile page, not the community page.

**Comment by billiedemott** [comment]
Hey, 

I actually think that when you login, you should see the community page, not your journal page. The community stream is much more active and reading other people's posts incites you to write. That's how I feel, but what were your thoughts? Why were you thinking it should go to your journal? We can test this out too.

**Comment by akshatpradhan** [comment]
After I add an entry, I want to read my newest  entry and compare it to one of my old entries. 

I feel irritated that it takes me to the community page. I already scanned all those anonymous posts. I don't want to see it again. After I journal, it's about me at that point. 

But if you feel otherwise, we can close the ticket. 

;Akshat

**Comment by billiedemott** [comment]
@akshatpradhan - yeah, I totally agree that after you write an entry that it should take you should be taken to your journal. But when you just log into the site, then I think you should be taken to the community page. 

So I agree with this: 

Given I'm on http://www.spoutlets.com
When I log an entry and submit, 
Then I should see my profile page, not the community page.

I think we are thinking the same thing.

**Comment by akshatpradhan** [comment]
I think I'm stupid. This is already happening, not sure what I'm thinking. 

;Akshat

**Comment by billiedemott** [comment]
@akshatpradhan - i think the only numbskull thing that's been said is the above <:). Lots of things to keep track of.
