### ISSUE TITLE
Therapist Account Creation Copy

### ISSUE THREAD

**Issue by billiedemott** [akshatpradhan/spoutlets#93]
I'm a Therapist.

Given a User has invited me via email
When I click the invitation link in the email: <a href="http://localhost:3000/therapists/invitation/accept? invitation_token=7q7whRyYwiGxvsKA4NF6)"> Click to view Journal.</a>

Then I see this page. 

![screen shot 2013-07-09 at 8 10 10 pm](https://f.cloud.github.com/assets/331004/771954/4e80a23a-e8f5-11e2-87c5-9d23c2999d6a.png)

This is basically the therapist account creation page. Can you make this page look better? We need better copy, something that's more informative to the Therapist, like

**How's it going? Akshat has invited you to see his Journal. Create an account to access his journal**

Or something like that. I imagine Dropbox and Dropmark have informative account creation pages that tell the user what they do, what they have access to, and then after they create an account, what page do they go do? For this case, it would be the Therapist's profile page right? 

Given a user has invited me via email
When I create my account

![screen shot 2013-07-09 at 8 10 10 pm](https://f.cloud.github.com/assets/331004/771954/4e80a23a-e8f5-11e2-87c5-9d23c2999d6a.png)

Then I see this page.

![screen shot 2013-07-08 at 7 42 57 pm](https://f.cloud.github.com/assets/1459738/765310/2332c52c-e828-11e2-88b5-3b9095ae6257.png)

It might be good to go through the old therapist wireframes you made before for inspiration.

If you could have this done asap, that would be great. It's somewhat of a critical blocker.

**Comment by billiedemott** [comment]
@akshatpradhan  - I'm on it. And I think we should keep all these in Github! Why enter another tool into the mix, right? Github's great and I want to get used to using it.

**Comment by akshatpradhan** [comment]
close https://github.com/akshatpradhan/spoutlets/pull/121
