### ISSUE TITLE
Which entries are public/private?

### ISSUE THREAD

**Issue by akshatpradhan** [akshatpradhan/spoutlets#94]
As a User
I want to see which entries are public and which ones aren't.
So that I can turn a private entry into a public entry

I ask because I want to make a few of my entries public, and I don't know/remember which ones are public already and which ones are private.

What's the most intuitive way that should look?
Sketch, take a picture w/ your iPhone, and upload it here please

![screen shot 2013-07-10 at 6 42 05 pm](https://f.cloud.github.com/assets/331004/778483/14206482-e9b2-11e2-8889-8fbb70d0e4f2.png)

**Comment by billiedemott** [comment]
@akshatpradhan - this is what I've always liked to demarcate what's private and what's public. This is from Bitly:
1. The lock "unlocked" shows that the entry has been shared. If the user hovers over it, then it says "Shared."

![screen shot 2013-07-10 at 7 42 12 pm](https://f.cloud.github.com/assets/1459738/778793/ed35852e-e9ba-11e2-93a9-90a222483796.png)
1. The lock "locked" shows that the entry is private. If the user hovers over it, then it says "Kept Private."

![screen shot 2013-07-10 at 7 42 56 pm](https://f.cloud.github.com/assets/1459738/778798/136a9b44-e9bb-11e2-966b-c95a525da403.png)
1. If the entry is shared with the community and "shared with a therapist," then lock in the "unlocked" state should be a different color (we can figure that out later). If a user hovers over this lock, then the tooltip says "Shared with Community & Therapist."
2. If the entry is kept private and "shared with therapist," then the lock in the "locked" state should be a different color. If a user hovers over this lock, then the tooltip says "Kept Private btw You and Your Therapist."

We could use these icons for the time being. They're cheap. 

http://thenounproject.com/noun/lock/#icon-No1813

http://thenounproject.com/noun/lock/#icon-No1812

**Comment by akshatpradhan** [comment]
Ok, where on the page does it go?

**Comment by billiedemott** [comment]
@akshatpradhan  - See below. I think this clarifies things. The lock is just a symbol of what's been shared with your community, what's been shared with your community & your shrink, what's been kept private & what's been kept private between you and your therapist. It shouldn't navigate to any page. If a user wants to share the entry, then they can press the "edit" button. At least for now, I think that route is fine. (Eventually we can filter by these categories, but that definitely should take less precedent over being able to filter your journal by entry categories, ie work/school, health, etc.)

![screen shot 2013-07-10 at 8 31 44 pm](https://f.cloud.github.com/assets/1459738/778994/8d34d240-e9c1-11e2-9ec2-02fa4d294d0a.png)

**Tooltips with the Copy For Each State of an Entry**

![screen shot 2013-07-10 at 8 37 21 pm](https://f.cloud.github.com/assets/1459738/779006/154b5f32-e9c2-11e2-9ff5-a119df19159f.png)

![screen shot 2013-07-10 at 8 40 24 pm](https://f.cloud.github.com/assets/1459738/779018/7cf4710a-e9c2-11e2-93a3-df040740a9a3.png)

**Comment by akshatpradhan** [comment]
This looks interesting, I like it, but do you think it would look better here? I ask because I recollect an interesting article about how notices on the left and actions on the right are better for IA.
![screenshot_7_10_13_8_45_pm](https://f.cloud.github.com/assets/331004/779053/aed5c77c-e9c3-11e2-8f12-4aff503ceee8.png)

**Comment by billiedemott** [comment]
Hey, 

Yeah, I like that position too! And I think it's unobtrusive enough, so it works there. Take a look: 

![screen shot 2013-07-10 at 9 03 53 pm](https://f.cloud.github.com/assets/1459738/779100/ec0db06c-e9c5-11e2-9e1e-aac3b1689e70.png)

**Comment by akshatpradhan** [comment]
Here's how it looks so far, any hypotheses?
![screen shot 2013-07-11 at 12 11 00 pm](https://f.cloud.github.com/assets/331004/782959/a9e791d8-ea44-11e2-9ebd-d4e2bf141c40.png)

**Comment by billiedemott** [comment]
Umm, basically I THINK THIS LOOKS AWESOMMMMMMMMMMMMMMMEEEE!

On Thu, Jul 11, 2013 at 12:12 PM, Akshat Pradhan
notifications@github.comwrote:

> Here's how it looks so far, any hypotheses?
> [image: screen shot 2013-07-11 at 12 11 00 pm]https://f.cloud.github.com/assets/331004/782959/a9e791d8-ea44-11e2-9ebd-d4e2bf141c40.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/akshatpradhan/spoutlets/issues/94#issuecomment-20823260
> .

## 

Billie DeMott
(646) 209-3101

_"Without anxiety and illness I should have been like a ship without a
rudder." *
*- Edvard Munch_
