### ISSUE TITLE
Where does a Therapist login from?

### ISSUE THREAD

**Issue by akshatpradhan** [akshatpradhan/spoutlets#95]
Given I'm a Therapist
When I'm on the Homepage
How do I login?

Note the constraints in the image below

![screen shot 2013-07-10 at 6 57 42 pm](https://f.cloud.github.com/assets/331004/778578/29fb1b92-e9b4-11e2-9ae8-128bd7ccc70a.png)

**Comment by billiedemott** [comment]
@akshatpradhan - working on this. I made these userflows & page inventory. I'm working on the things in the page inventory. 

![screen shot 2013-07-11 at 8 53 11 pm](https://f.cloud.github.com/assets/1459738/785755/8f19c486-ea8d-11e2-82c9-04f2415e12e5.png)

![screen shot 2013-07-11 at 8 55 25 pm](https://f.cloud.github.com/assets/1459738/785768/c3955bf8-ea8d-11e2-8780-2fdb355ba403.png)

**Comment by billiedemott** [comment]
How Zocdoc onboards doctors:

![screen shot 2013-07-11 at 8 59 41 pm](https://f.cloud.github.com/assets/1459738/785782/598d5688-ea8e-11e2-9293-a93335dd076b.png)

![screen shot 2013-07-11 at 9 00 06 pm](https://f.cloud.github.com/assets/1459738/785784/6527aac0-ea8e-11e2-81c1-7cf9d6f4c143.png)

![screen shot 2013-07-11 at 9 00 23 pm](https://f.cloud.github.com/assets/1459738/785786/72907192-ea8e-11e2-8190-d0cdb1653596.png)

(They have a "sign up now" button at the button of the "How it works" page. 
![screen shot 2013-07-11 at 9 00 43 pm](https://f.cloud.github.com/assets/1459738/785788/79ed16fc-ea8e-11e2-8656-613b584398d4.png)

![screen shot 2013-07-11 at 9 01 16 pm](https://f.cloud.github.com/assets/1459738/785791/8cf0c1ae-ea8e-11e2-9341-18cfe2dcf9ab.png)

Think eventually we can use this for inspiration.

**Comment by akshatpradhan** [comment]
There are some restraints, I drew it below:

 You can also change the navigation at the top to whatever you want as well.
![screenshot_7_12_13_5_02_pm](https://f.cloud.github.com/assets/331004/791044/01ecf448-eb37-11e2-8351-e3fef7b7f36c.png)

**Comment by billiedemott** [comment]
@akshatpradhan Great! Thank you for this explanation re: constraint.

**Comment by akshatpradhan** [comment]
We're going to solve this UX flow problem by doing this:
![screen shot 2013-09-24 at 5 46 52 pm](https://f.cloud.github.com/assets/331004/1220591/7aba8dea-26dd-11e3-85b1-0227386c6298.png)
